version: '3.8'

services:
  backend:
    build:
      context: ./nestjs-project
      dockerfile: Dockerfile
    container_name: nestjs-backend
    ports:
      - "3000:5000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_SERVER: postgres-db
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
